App/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('Auth.urls')),
    path('', include('Menu.urls')),
    path('', include('Base.urls')),
    path('', include('Blog.urls')),
    path('orders/', include('Order.urls')),
    path('reviews/', include('Reviews.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Reviews/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/', views.FormReview.as_view(), name='add_comment')    
]

Reviews/models.py
from django.db import models
from Auth.models import User
from Menu.models import Menu
import datetime
# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=200, null=True)
    comment = models.TextField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, )
    created_at = models.DateTimeField(default=datetime.datetime.now)
    
    class Meta:
        verbose_name = 'review'
        verbose_name_plural = 'reviews'
        
        
    def __str__(self):
        return self.title 
    

Reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.Form):
    title = forms.CharField(
        label='title',
        required= True,
        max_length=100,
        widget=forms.TextInput(attrs={'class' : 'w-full rounded-md p-2 my-2', 'placeholder' : 'Nombre del comentario'}),
    )
    comment = forms.CharField(
        label='comment',
        required=True,
        max_length=500,       
        widget=forms.Textarea(attrs={'class' : 'w-full rounded-md p-2 my-2', 'placeholder' : 'Descripticion del comentario'})
    )

Reviews/views.py
from django.views.generic import ListView, FormView
from  .models import Review
from .forms import ReviewForm
from django.shortcuts import redirect
from Auth.models import User
from .mixins import HasReviewMixin

# Create your views here.
class ListComments(ListView):
    template_name = 'reviews.html',
    context_object_name = 'reviews'
    model = Review
    queryset = Review.objects.all()

    
class FormReview(HasReviewMixin, FormView):
    form_class = ReviewForm
    template_name = 'form_review.html'
    login_url = '/accounts/login/'
    success_url = '/'
        
    def form_valid(self, form):
        title = form.cleaned_data['title']
        comment = form.cleaned_data['comment']
        user = self.request.user
  
        existing_review = Review.objects.filter(title=title, user=user).first()

        if existing_review:
           
            existing_review.comment = comment
            existing_review.save()
        else:
           
            new_review = Review(title=title, comment=comment, user=user)
            new_review.save()

        return redirect(self.success_url)

Reviews/templates/form_review.html
{% extends "base.html" %}

{% load static %}
{% block content %}
{% include  'navBar.html' %}
<main class="w-[90%] mx-auto md:w-[50%] bg-amber-800 h-full py-10 mt-[20rem] md:mt-20 ">

    <form action="{% url 'add_comment' %}" method="POST" class="mt-8">
        {% csrf_token %}
        <label class="text-white">{{ form.title.label}} </label>
        {{ form.title }}
        <label class="text-white">{{ form.comment.label}} </label>
        {{ form.comment }}

        <button class="w-full  bg-amber-500 hover:bg-amber-600 text-white p-2 rounded-md font-bold" type="submit">Add Comment</button>
    </form>
</main>
{% endblock content %}

Reviews/templates/reviews.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<main class="bg-amber-800 h-full py-10">
  <div class="w-[90%] mx-auto lg:w-[70%]">
    {% if request.user.is_authenticated %}
    {% with user_reviews=request.user.review_set.all %}
        {% if user_reviews %}
            {% for review in user_reviews %}
                <p></p>
            {% endfor %}
        {% else %}
            <div class="flex gap-2 justify-end">
                <a class="text-white font-bold" href="{% url 'add_comment' %}">Add comment</a>
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd" d="M2 12a10 10 0 1 1 20 0 10 10 0 0 1-20 0Zm11-4.2a1 1 0 1 0-2 0V11H7.8a1 1 0 1 0 0 2H11v3.2a1 1 0 1 0 2 0V13h3.2a1 1 0 1 0 0-2H13V7.8Z" clip-rule="evenodd"/>
                </svg>
            </div>            
        {% endif %}
    {% endwith %}
{% endif %}
    {% for review in reviews %}
        <div class="bg-white p-4 rounded-md my-4">
            <p class="font-extrabold ">{{ review.title }}|<span class="text-amber-500">{{ review.created_at }}</span><p>
             <div class="mt-4 flex justify-between ">
                <p class="">{{ review.comment }}</p>

                <div class="flex flex-col justify-end">

                    <p class="text-amber-500 font-bold">{{ review.user.username }}</p>
                </div>
             </div>   
        </div>
    {% endfor %}
  </div>
</main>
{% endblock content %}